spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5431}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect # enable proper handling of gis types
    hibernate:
      ddl-auto: update  # could change to create-drop when need drop schema every time the app restarts
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # for dev
